global:
  scrape_interval: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
    # whatever you want
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
      labels:
        alias: 'prometheus'
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
      labels:
        alias: 'cadvisor'
  - job_name: 'node'
    static_configs:
    - targets: ['node-exporter:9100']
      labels:
        alias: 'node'
  - job_name: 'jdbc-demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['jdbc:8000']
      labels:
        alias: 'jdbc-demo'
  - job_name: 'r2dbc-demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['r2dbc:8001']
      labels:
        alias: 'r2dbc-demo'
  - job_name: 'postgres-exporter'
    static_configs:
    - targets: ['postgres-exporter:9187']
      labels:
        alias: 'postgres-exporter'
  # - job_name: 'cadvisor'
  #   static_configs:
  #   - targets: ['cadvisor:8080']
  #     labels:
  #       alias: 'cadvisor'
  # - job_name: node
  #   static_configs:
  #     - targets: ['node-exporter:9100']
